# Generated by Django 4.0.6 on 2022-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0001_initial'),
        ('users', '0002_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(to='circle.relationship'),
        ),
    ]
