# Generated by Django 4.0.6 on 2022-09-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('users', '0003_user_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.digitalwallet'),
        ),
    ]
