# Generated by Django 4.0.6 on 2022-09-14 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.PositiveBigIntegerField(default=0)),
                ('dollar', models.FloatField(default=0.0)),
            ],
        ),
    ]
